import React, { useState, useEffect } from 'react';
import { 
  BookOpen, 
  Scale, 
  ShieldAlert, 
  Layers, 
  Info, 
  CheckCircle2, 
  AlertTriangle,
  Compass,
  FileText,
  Landmark,
  TrendingUp,
  Clock
} from 'lucide-react';
import { SystemAPI } from '../services/api';
import LoadingState from '../components/common/LoadingState';

export const MethodologyPage = () => {
  const [methodology, setMethodology] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    const fetchMethodology = async () => {
      setLoading(true);
      setError(null);
      try {
        const data = await SystemAPI.getMethodology();
        setMethodology(data);
      } catch (err) {
        console.error('Failed to load methodology disclosure:', err);
        setError(err.message || 'Failed to fetch methodology parameters from backend.');
      } finally {
        setLoading(false);
      }
    };

    fetchMethodology();
  }, []);

  if (loading) {
    return (
      <div className="py-12">
        <LoadingState message="Loading analytical methodology framework and transparency parameters..." />
      </div>
    );
  }

  if (error || !methodology) {
    return (
      <div className="py-12 text-center text-red-600 space-y-2">
        <AlertTriangle className="w-10 h-10 text-red-500 mx-auto" />
        <p className="font-semibold text-sm">{error || 'Methodology information unavailable.'}</p>
      </div>
    );
  }

  return (
    <div className="space-y-8 py-6 max-w-7xl mx-auto">
      {/* Header */}
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center pb-4 border-b border-slate-200 gap-4">
        <div>
          <h1 className="text-2xl font-bold text-slate-900 flex items-center gap-2">
            <BookOpen className="w-6 h-6 text-gov-navy" />
            Methodology & Transparency Framework
          </h1>
          <p className="text-xs text-slate-500 mt-1">
            Explainable formulation, statistical cohort baselines, data boundaries, and Responsible AI guidelines (v{methodology.version})
          </p>
        </div>
        <span className="text-xs font-mono font-bold text-gov-navy bg-blue-50 px-3 py-1.5 rounded-md border border-blue-200">
          Model A: Pure Additive (Max 100)
        </span>
      </div>

      {/* Primary Responsible AI Disclaimer Banner */}
      <div className="p-4 bg-amber-50 rounded-lg border-l-4 border-l-amber-500 border border-amber-200 text-amber-950 space-y-2 shadow-sm">
        <div className="flex items-center gap-2 font-bold text-sm text-amber-900">
          <ShieldAlert className="w-5 h-5 text-amber-600 flex-shrink-0" />
          Responsible AI & Analytical Review Signal Disclosure
        </div>
        <p className="text-xs leading-relaxed text-amber-900">
          <strong>Mandatory Principle: </strong>{methodology.disclaimer}
          <span className="block mt-1">
            Risk scores, statistical deviations, and reason cards generated by this platform are analytical review signals designed to prioritize administrative inspection. A statistical outlier or review flag does <strong>NOT</strong> indicate corruption, fraud, misuse of funds, or administrative guilt.
          </span>
        </p>
      </div>

      {/* Data Scope & Boundaries Card */}
      <div className="gov-card p-6 space-y-4">
        <h3 className="text-sm font-bold text-slate-900 flex items-center gap-2 pb-2 border-b border-slate-100">
          <Landmark className="w-4 h-4 text-gov-navy" />
          Data Boundaries & Unit of Observation
        </h3>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs">
          <div className="p-3.5 bg-slate-50 rounded-lg border border-slate-200 space-y-1.5">
            <span className="font-bold text-slate-900 block">1. Unit of Observation</span>
            <p className="text-slate-600 leading-relaxed">
              The dataset represents <strong>Constituency-Level Parliamentary Term Work & Fund Allocations</strong> (15th, 16th, and 17th Lok Sabha sessions). Records represent aggregated parliamentary allocations rather than granular individual physical construction work-sites.
            </p>
          </div>

          <div className="p-3.5 bg-slate-50 rounded-lg border border-slate-200 space-y-1.5">
            <span className="font-bold text-slate-900 block">2. Record Identifiers & Descriptions</span>
            <p className="text-slate-600 leading-relaxed">
              The <code className="text-gov-navy font-semibold">source_record_id</code> is a dataset record identifier assigned during ingestion, not a verified government-issued work ID. Field descriptions represent allocation-level labels.
            </p>
          </div>

          <div className="p-3.5 bg-slate-50 rounded-lg border border-slate-200 space-y-1.5">
            <span className="font-bold text-slate-900 block">3. Financial Utilization Proxy</span>
            <p className="text-slate-600 leading-relaxed">
              Utilization is calculated strictly as <code className="text-gov-navy font-semibold">(Reported Expenditure / Sanctioned Cost) × 100</code>. It serves as a financial disbursement proxy and <strong>MUST NOT</strong> be construed as physical civil construction progress.
            </p>
          </div>

          <div className="p-3.5 bg-slate-50 rounded-lg border border-slate-200 space-y-1.5">
            <span className="font-bold text-slate-900 block">4. Geospatial Centroids</span>
            <p className="text-slate-600 leading-relaxed">
              Geographic coordinates represent verified administrative <strong>district reference centroids</strong> (100% matched), not exact physical project GPS locations or construction site tracking.
            </p>
          </div>
        </div>
      </div>

      {/* Composite Risk Score Formulation */}
      <div className="gov-card p-6 space-y-5">
        <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center pb-2 border-b border-slate-100 gap-2">
          <div>
            <h3 className="text-sm font-bold text-slate-900 flex items-center gap-2">
              <Scale className="w-4 h-4 text-gov-navy" />
              Composite Mathematical Formulation
            </h3>
            <p className="text-xs text-slate-500">Pure linear additive formulation with transparent explainability</p>
          </div>
          <div className="font-mono text-xs font-bold text-gov-navy bg-slate-100 px-3 py-1 rounded">
            {methodology.composite_formula}
          </div>
        </div>

        {/* Dimension Breakdown Cards */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {methodology.components.map((comp) => (
            <div key={comp.dimension} className="p-4 rounded-lg bg-slate-50 border border-slate-200 space-y-2 flex flex-col justify-between">
              <div>
                <div className="flex justify-between items-start">
                  <h4 className="text-xs font-bold text-slate-900">{comp.dimension}</h4>
                  <span className="text-xs font-black text-gov-navy bg-white px-2 py-0.5 rounded border border-slate-200">
                    {comp.weight} pts
                  </span>
                </div>
                <p className="text-[11px] text-slate-600 mt-1 leading-relaxed">
                  {comp.description}
                </p>
              </div>

              <div className="pt-2 border-t border-slate-200 text-[10px] space-y-1">
                <div className="text-slate-500">
                  <span className="font-semibold">Cohort Basis: </span>{comp.cohort_basis}
                </div>
                <div className="font-mono text-gov-navy bg-white p-1.5 rounded border border-slate-200 break-all">
                  {comp.formula}
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Risk Tiers & Thresholds */}
      <div className="gov-card p-6 space-y-4">
        <h3 className="text-sm font-bold text-slate-900 flex items-center gap-2 pb-2 border-b border-slate-100">
          <Layers className="w-4 h-4 text-gov-navy" />
          Standard Risk Tiers & Activation Bands
        </h3>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
          <div className="p-4 rounded-lg bg-emerald-50/70 border border-emerald-200 space-y-1">
            <span className="gov-badge-low font-bold text-xs">Low Risk (0.0 – 24.9)</span>
            <p className="text-[11px] text-emerald-950 mt-1">
              Normal statistical cohort parameters. Expenditure within median peer baseline. Zero administrative compliance flags.
            </p>
          </div>

          <div className="p-4 rounded-lg bg-yellow-50/70 border border-yellow-200 space-y-1">
            <span className="gov-badge-medium font-bold text-xs">Medium Risk (25.0 – 49.9)</span>
            <p className="text-[11px] text-yellow-950 mt-1">
              Moderate single-dimension deviation, multi-year active retention without disbursement, or audit certificate documentation notations.
            </p>
          </div>

          <div className="p-4 rounded-lg bg-amber-50/70 border border-amber-200 space-y-1">
            <span className="gov-badge-high font-bold text-xs">High Risk (50.0 – 74.9)</span>
            <p className="text-[11px] text-amber-950 mt-1">
              Compounding multi-signal outlier or significant financial deviation exceeding localized (Category, State) P90 cohort thresholds with ratio ≥ 1.30.
            </p>
          </div>

          <div className="p-4 rounded-lg bg-red-50/70 border border-red-200 space-y-1">
            <span className="gov-badge-critical font-bold text-xs">Critical Risk (75.0 – 100.0)</span>
            <p className="text-[11px] text-red-950 mt-1">
              Severe multi-dimensional compounding anomaly across all criteria (Financial + Timeline + Compliance + Spatial).
            </p>
          </div>
        </div>
      </div>

      {/* Cohort Quantile & Fallback Hierarchy Card */}
      <div className="gov-card p-6 space-y-4">
        <h3 className="text-sm font-bold text-slate-900 flex items-center gap-2 pb-2 border-b border-slate-100">
          <TrendingUp className="w-4 h-4 text-gov-navy" />
          Statistical Cohort Hierarchy & Fallback Rules
        </h3>

        <div className="space-y-3 text-xs leading-relaxed text-slate-700">
          <p>
            To prevent distortion from state-level policy variations and sector scale, allocations are grouped into statistical cohorts defined primarily by <code className="text-gov-navy font-semibold">(Civic Category, State)</code>.
          </p>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-3 pt-2">
            <div className="p-3 bg-slate-50 rounded border border-slate-200">
              <span className="font-bold text-slate-900 block mb-1">Primary Cohort (N ≥ 10)</span>
              <p className="text-slate-600 text-[11px]">
                Localized Category + State peer group. Covers 94.6% of allocations with granular regional cost baselines.
              </p>
            </div>

            <div className="p-3 bg-slate-50 rounded border border-slate-200">
              <span className="font-bold text-slate-900 block mb-1">Category Fallback (N &lt; 10)</span>
              <p className="text-slate-600 text-[11px]">
                National Category-wide baseline applied automatically when local cohort size is insufficient to prevent small-sample noise.
              </p>
            </div>

            <div className="p-3 bg-slate-50 rounded border border-slate-200">
              <span className="font-bold text-slate-900 block mb-1">Dual Trigger Condition</span>
              <p className="text-slate-600 text-[11px]">
                Cost anomaly strictly requires <code className="text-gov-navy">exp &gt; P90</code> AND <code className="text-gov-navy">exp / P50 ≥ 1.30</code> to eliminate false positives in tight distributions.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default MethodologyPage;
